# Generated by Django 5.1.5 on 2025-01-28 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
